Домашнее задание 10
Aristman/Filmoteca pull request #19
Opened 2021-08-28 15:29 UTC by Aristman

API для доступа к сервисам нужно прописать в локальном файле local.properties.
Создан фрагмент с картой, реализовано получение разрешений от пользователя через отдельный класс. На этот же класс повешено получение разрешений для телефонной книги.
В строке поиска можно вводить название или адрес. А можно ввести два числа через пробел - тогда будет поиск по координатам с выводом сообщения о найденном адресе.

2021-08-28 15:57 UTC, sergfirago requested changes

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/domain/util/Extentions.kt
> +        val splitString = this.split(" ")
в константы

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +    private var mapLocation: MutableLiveData<LatLng?> = MutableLiveData(null)
?

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +        requestLocationPermission.permission.observeForever { permission ->
.observeForever ?

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +        requestLocationPermission.permission.observeForever { permission ->
возможен краш

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +        binding.addressFindButton.setOnClickListener {
сделать рефакторинг

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +        lifecycle.coroutineScope.launch(Dispatchers.IO) {
lifecycleScope

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +                e.printStackTrace()
выводить в Log или Timber

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/phonebook/PhonebookFragment.kt
> +        contactsRequestPermission.permission.observeForever { permissionStatus ->
observeForever ?

2021-08-28 15:57 UTC, sergfirago commented on app/src/main/java/ru/marslab/filmoteca/ui/phonebook/PhonebookFragment.kt
>      private fun getContacts() {
в репозиторий

2021-08-28 16:10 UTC, Aristman commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +    private var mapLocation: MutableLiveData<LatLng?> = MutableLiveData(null)
Решение не самое хорошее, но нужно было или вводить коллбэк свой на асинхронное выполнение. Это решение мне показалось оптимальным. В дальнейшем все данные будут перенесены во вьюмодель

2021-08-28 16:17 UTC, Aristman commented on app/src/main/java/ru/marslab/filmoteca/ui/phonebook/PhonebookFragment.kt
>      private fun getContacts() {
Эта работа будет сделана на следующем этапе. Для двух фрагментов Maps b PhoneBook будут созданы вьюмодели и вся работа с данными будет через репозитории.

2021-08-30 10:51 UTC, DeltAagent00 commented on app/src/main/java/ru/marslab/filmoteca/ui/googlemap/MapsFragment.kt
> +        if (findFromLocationLatLng.size > 0) {
Вместо size > 0 использовать isNotEmpty

2021-08-30 15:29 UTC, merged